name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
         docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/testing:latest ./github-action-02  # Current directory (.) is the context
         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/testing:latest


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name github-action \
            --resource-group online-mart-api \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/testing:latest 
         
